<?php

declare(strict_types=1);

namespace App\Generator\TypeScript;

use App\Generator\Writer\FileWriter;
use App\Generator\Config\GeneratorConfiguration;

/**
 * Base class for all TypeScript generators.
 *
 * Provides common utilities for:
 * - File writing
 * - Indentation
 * - Comment generation
 * - Import management
 */
abstract class CoreGenerator
{
    public function __construct(
        protected readonly FileWriter $fileWriter,
        protected readonly GeneratorConfiguration $config,
    ) {}

    /**
     * Generates the TypeScript files.
     * Must be implemented by concrete generators.
     *
     * @param mixed $data Data to generate from (varies by generator)
     */
    abstract public function generate(mixed $data = null): void;

    /**
     * Writes content to a file.
     */
    protected function write(string $relativePath, string $content): void
    {
        $this->fileWriter->write($relativePath, $content);
    }

    /**
     * Generates a file header with warning comment.
     */
    protected function generateFileHeader(string $description = ''): string
    {
        $header = "/**\n";
        $header .= " * AUTO-GENERATED FILE - DO NOT EDIT\n";

        if ($description !== '') {
            $header .= " * \n";
            $header .= " * {$description}\n";
        }

        $header .= " * \n";
        $header .= " * Generated by: php bin/console app:generate-nuxt-interface\n";
        $header .= " */\n\n";

        return $header;
    }

    /**
     * Generates TypeScript imports.
     *
     * @param array<string, string[]> $imports Module path => imported names
     */
    protected function generateImports(array $imports): string
    {
        if (empty($imports)) {
            return '';
        }

        $lines = [];

        foreach ($imports as $module => $names) {
            if (empty($names)) {
                continue;
            }

            $importList = implode(', ', $names);
            $lines[] = "import type { {$importList} } from '{$module}'";
        }

        return implode("\n", $lines) . "\n\n";
    }

    /**
     * Indents a block of code.
     */
    protected function indent(string $code, int $level = 1): string
    {
        $indentation = str_repeat('  ', $level);
        $lines = explode("\n", $code);

        return implode("\n", array_map(
            fn(string $line) => $line !== '' ? $indentation . $line : $line,
            $lines
        ));
    }

    /**
     * Generates a JSDoc comment.
     *
     * @param string[] $lines
     */
    protected function generateJsDoc(array $lines, int $indentLevel = 0): string
    {
        if (empty($lines)) {
            return '';
        }

        $doc = "/**\n";

        foreach ($lines as $line) {
            $doc .= " * {$line}\n";
        }

        $doc .= " */\n";

        return $this->indent($doc, $indentLevel);
    }

    /**
     * Escapes a string for use in TypeScript.
     */
    protected function escapeString(string $string): string
    {
        return addslashes($string);
    }

    /**
     * Generates a TypeScript interface.
     *
     * @param array<string, string> $properties property name => type
     */
    protected function generateInterface(
        string $name,
        array $properties,
        ?string $description = null,
        bool $export = true,
    ): string {
        $code = '';

        if ($description !== null) {
            $code .= $this->generateJsDoc([$description]);
        }

        $exportKeyword = $export ? 'export ' : '';
        $code .= "{$exportKeyword}interface {$name} {\n";

        foreach ($properties as $propName => $propType) {
            $code .= "  {$propName}: {$propType}\n";
        }

        $code .= "}\n";

        return $code;
    }

    /**
     * Generates a TypeScript type alias.
     */
    protected function generateTypeAlias(
        string $name,
        string $type,
        ?string $description = null,
        bool $export = true,
    ): string {
        $code = '';

        if ($description !== null) {
            $code .= $this->generateJsDoc([$description]);
        }

        $exportKeyword = $export ? 'export ' : '';
        $code .= "{$exportKeyword}type {$name} = {$type}\n";

        return $code;
    }

    /**
     * Generates a constant export.
     */
    protected function generateConstant(
        string $name,
        string $value,
        string $type,
        ?string $description = null,
    ): string {
        $code = '';

        if ($description !== null) {
            $code .= $this->generateJsDoc([$description]);
        }

        $code .= "export const {$name}: {$type} = {$value}\n";

        return $code;
    }

    /**
     * Formats a TypeScript object literal.
     *
     * @param array<string, mixed> $data
     */
    protected function formatObject(array $data, int $indentLevel = 0): string
    {
        if (empty($data)) {
            return '{}';
        }

        $lines = [];
        $lines[] = '{';

        foreach ($data as $key => $value) {
            $formattedValue = $this->formatValue($value, $indentLevel + 1);
            $lines[] = $this->indent("{$key}: {$formattedValue},", $indentLevel + 1);
        }

        $lines[] = $this->indent('}', $indentLevel);

        return implode("\n", $lines);
    }

    /**
     * Formats a value for TypeScript.
     */
    protected function formatValue(mixed $value, int $indentLevel = 0): string
    {
        if (is_string($value)) {
            return "'{$this->escapeString($value)}'";
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_null($value)) {
            return 'null';
        }

        if (is_numeric($value)) {
            return (string) $value;
        }

        if (is_array($value)) {
            return $this->formatObject($value, $indentLevel);
        }

        return 'undefined';
    }
}
